# Generated by Django 4.1.5 on 2023-01-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="stars",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "One"), (2, "Two"), (3, "Three"), (4, "Four"), (5, "Five")]
            ),
        ),
    ]
