# Generated by Django 4.1.5 on 2023-01-10 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
