# Generated by Django 4.1.5 on 2023-01-06 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Overview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=6
                    ),
                ),
                ("height", models.DecimalField(decimal_places=2, max_digits=3)),
                ("weight", models.DecimalField(decimal_places=1, max_digits=4)),
                ("bmi", models.DecimalField(decimal_places=2, max_digits=4)),
                ("whr", models.DecimalField(decimal_places=2, max_digits=3)),
                ("lean_mass", models.DecimalField(decimal_places=2, max_digits=4)),
                ("fat_mass", models.DecimalField(decimal_places=2, max_digits=4)),
                ("body_fat", models.DecimalField(decimal_places=2, max_digits=4)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
