# Generated by Django 4.1.5 on 2023-01-05 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sheet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_sheet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
