# Generated by Django 4.1.5 on 2023-01-04 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="uuid",
        ),
        migrations.AddField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cb4c66ea-cb6d-40aa-bdb7-c88ec1878f7f"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
